#!/usr/bin/env sh

if cp -r webtree /usr/local/lib
then
	echo "Operation Complete..."
else
	echo "Directory already exists. Do you want to overwrite?"
	select choice in "Yes" "No"
	do
		case $choice in
			Yes ) rm -f webtree
			      echo "deteting existing files..."
			      cp -r webtree /usr/local/lib
			      echo "Operation Complete..."
			      break;;
			No ) exit 0;;
		esac
	done	
fi

ln -s /usr/local/lib/webtree/webtree /usr/local/bin/webtree


echo SUCCESSFULLY INSTALLED
